spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: 
        health:
          repositories:
            movie:
              label: master
            rating:
              label: master
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: config-99.cfapps.io
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-kb.cfapps.io/eureka/

---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: 
        health:
          repositories:
            movie:
              label: master
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---

spring:
  profiles: lattice
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: 
        health:
          repositories:
            movie:
              label: lattice
            rating:
              label: lattice
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost:8888}
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.54.149.244.237.xip.io/eureka/